services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
  web:
    build:
      context: ./rapi
      dockerfile: ./rapi/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
