# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.0'
gem 'sqlite3', '~> 1.4'
gem 'redis-client', '~> 0.22.1'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'

  gem 'simplecov'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

